### ISSUE TITLE
我看到有两个版本

### ISSUE THREAD

**Issue by ghost** [vulnspy/ECShop_3.6.0_UTF8_installed#1]
这个版本动了哪里。 为什么复现不了。

**Comment by ambulong** [comment]
区别如下：

https://github.com/vsplate/env/blob/master/ECShop_3.6.0_UTF8_vuln_installed/html/ecshop/includes/lib_insert.php#L140

https://github.com/vsplate/env/blob/master/ECShop_3.6.0_UTF8_installed/html/ecshop/includes/lib_insert.php#L140

官网下载的3.6.0已被修复，在 ECShop_3.6.0_UTF8_vuln_installed 直接把修复的地方给注释掉了。

**Comment by ghost** [comment]
> 
> 
> 区别如下：
> 
> https://github.com/vsplate/env/blob/master/ECShop_3.6.0_UTF8_vuln_installed/html/ecshop/includes/lib_insert.php#L140
> 
> https://github.com/vsplate/env/blob/master/ECShop_3.6.0_UTF8_installed/html/ecshop/includes/lib_insert.php#L140
> 
> 官网下载的3.6.0已被修复，在 ECShop_3.6.0_UTF8_vuln_installed 直接把修复的地方给注释掉了。

感谢。

**Comment by ghost** [comment]
感谢
